name: CI

on:
  push:
  pull_request:

jobs:
  style_and_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install prerequisites
        run: pip install pre-commit
      - name: Run style checkers and linters
        run: pre-commit run --all-files
